// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isckfinksgotymwusoeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY2tmaW5rc2dvdHltd3Vzb2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTIzMzUsImV4cCI6MjA2OTI4ODMzNX0.O5osxddV8ns96Yz8RFxei5roCS4EltmCvYP-t64mz-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});